### PR TITLE
Update the webpage

### PR DESCRIPTION
**Pull request by rerobika**
JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
I miss some new API functions from this update. Are you sure this is generated from the current master?

**Comment by rerobika** [comment]
@LaszloLango Yes, I've generated the it from the latest master (9c10d82e4af5d38191e1ce6d947157b5ef69d687). Which new API function do you think is missing?

**Comment by LaszloLango** [comment]
@rerobika, e.g.: `jerry_binary_operation` and `jerry_binary_operation_t` (#2746 & #2751)

**Comment by LaszloLango** [comment]
My bad, they are added. I missed that before

**Pull request merged**
