### PR TITLE
Update the webpage

### PR DESCRIPTION
**Pull request by LaszloLango**
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
Depends on #2834

**Comment by LaszloLango** [comment]
#2834 is merged without any change, so this PR is ready for review, no need to update.

**Comment by LaszloLango** [comment]
Updated after #2821

**Comment by rerobika** [comment]
Still LGTM

**Pull request merged**
