### PR TITLE
Properly release property name collection in for-in opcode handler

### PR DESCRIPTION
**Pull request by dbatyai**
JerryScript-DCO-1.0-Signed-off-by: Dániel Bátyai dbatyai@inf.u-szeged.hu

### CODE REVIEW

**Comment by dbatyai** [comment]
Just realized this is not the correct fix, I'll have to double check this.

**Comment by dbatyai** [comment]
Here's the thing: the for-in implementation directly manages the ecma collection structure, instead of relying on the iterator to do so, which also means that it releases the collection on it's own way.

This feels wrong, but unfortunately it's not an easy fix. We can't store the iterator pointer as a compressed pointer on the stack, since the iterator may be 4 byte aligned.

So instead of fixing the entire problem I resorted to keeping it a quick fix, and simply release the header the appropriate way, through the pool allocator.

**Comment by LaszloLango** [comment]
@dbatyai what about adding a TODO or NOTE comment with this information you mentioned above?

**Comment by dbatyai** [comment]
Done.

**Pull request merged**
