### PR TITLE
Integrate LLVM's libfuzzer engine with JerryScript

### PR DESCRIPTION
**Pull request by renatahodovan**
JerryScript-DCO-1.0-Signed-off-by: Renata Hodovan reni@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
Could you add some documentation about the usage of this feature?

**Comment by renatahodovan** [comment]
@LaszloLango sure! Where should it be placed?
Note: as a result of this patch, a new binary named jerry-libfuzzer will be created, which has the cli interface provided by the underlying llvm version (documented here: https://llvm.org/docs/LibFuzzer.html). So our documentation should be at most a reference to the original description (IMHO).

**Comment by LaszloLango** [comment]
I'd suggest to put it into `docs/01.GETTING-STARTED.md` if a reference is enough.

**Comment by renatahodovan** [comment]
@LaszloLango Updated and rebased.

**Pull request merged**
