### PR TITLE
Fix getting array length in ecma_builtin_promise_do_{race, all}

### LINKED ISSUE #2700: Assertion 'ecma_is_value_integer_number (value)' failed in ecma_get_integer_from_value
###### Jerry version:

```
Checked revision: adb80c20

Build command: ./tools/build.py --clean --debug --compile-flag=-m32 --profile=es2015-subset --system-allocator=on --error-messages=on --logging=on
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
Promise.race(new Array(0xfffffffe)); 
```

###### Backtrace:

```
ICE: Assertion 'ecma_is_value_integer_number (value)' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c(ecma_get_integer_from_value):611.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
0xf7fd5059 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf7de1832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7de2cc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5655c93a in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x5659f587 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5659f5c1 in jerry_assert_fail (assertion=0x565e3948 "ecma_is_value_integer_number (value)", file=0x565e37ec "jerryscript/jerry-core/ecma/base/ecma-helpers-value.c", 
    function=0x565cd0d8 <__func__.3339.lto_priv.664> "ecma_get_integer_from_value", line=611) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565c419f in ecma_get_integer_from_value (value=1450137234) at jerryscript/jerry-core/ecma/base/ecma-helpers-value.c:611
#7  0x565814dd in ecma_builtin_promise_do_race (array=1450137299, capability=1450137331, ctor=1450137075) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-promise.c:208
#8  0x56582118 in ecma_builtin_promise_race_or_all (this_arg=1450137075, array=1450137299, is_race=true) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-promise.c:598
#9  0x56582184 in ecma_builtin_promise_race (this_arg=1450137075, array=1450137299) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-promise.c:628
#10 0x56581035 in ecma_builtin_promise_dispatch_routine (builtin_routine_id=62, this_arg_value=1450137075, arguments_list=0xffffd05c, arguments_number=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-promise.inc.h:42
#11 0x565a5c5d in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_PROMISE, builtin_routine_id=62, this_arg_value=1450137075, arguments_list_p=0xffffd05c, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:952
#12 0x565a5da8 in ecma_builtin_dispatch_call (obj_p=0x566f5610, this_arg_value=1450137075, arguments_list_p=0xffffd05c, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:977
#13 0x565ad4f1 in ecma_op_function_call (func_obj_p=0x566f5610, this_arg_value=1450137075, arguments_list_p=0xffffd05c, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:645
#14 0x5658c0df in opfunc_call (frame_ctx_p=0xffffd07c) at jerryscript/jerry-core/vm/vm.c:526
#15 0x56591b8a in vm_execute (frame_ctx_p=0xffffd07c, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3455
#16 0x56591d8d in vm_run (bytecode_header_p=0x566f55a0, this_binding_value=1450135939, lex_env_p=0x566f51b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3552
#17 0x5658bb82 in vm_run_global (bytecode_p=0x566f55a0) at jerryscript/jerry-core/vm/vm.c:227
#18 0x565b43b4 in jerry_run (func_val=1450137043) at jerryscript/jerry-core/api/jerry.c:544
#19 0x565b2d7c in main (argc=3, argv=0xffffd314) at jerryscript/jerry-main/main-unix.c:676
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2700.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by rerobika** [comment]
Note: Due to the memory limitations I cannot enclose the related regression test case. Putting it in the fail directory does not work either due to the exit code. Does anybody have a good idea for adding the test case?

**Comment by akosthekiss** [comment]
@rerobika Two questions
- Could you give an analysis why the proposed code gives valid integer length data when the existing code failes?
- Is it possible to change the test case so that it still triggers the reported error but can be added to the test suite?

**Comment by rerobika** [comment]
@akosthekiss 

- An array length is always an `uint32_t` number, and we can ensure that we work a valid array due to this assertion in the beginning of the function `JERRY_ASSERT (ecma_get_object_type (ecma_get_object_from_value (array)) == ECMA_OBJECT_TYPE_ARRAY);
`. The original code were trying to get the length property which is an `integer number` but not all cases. In the reported test case the array's length is `0xfffffffe` which is bigger than the `ECMA_INTEGER_NUMBER_MAX (0x7ffffff)` so it means the length property cannot be stored directly in an `ecma_integer_t` it needs to be wrapped to ecma_value_t which stores an `ecma_number_t` even when the number is still a valid integer. In addition this procedure is completely unnecessary, since the `length` property can be accessed directly from the `ecma_extended_object`.
- To reproduce the original issue the array's length enough to be `ECMA_INTEGER_NUMBER_MAX + 1`, but with this configuration I wasn't able to run the test with 128MB heap size either. So I think it is not possible to add this test to the test suite, but I'm still open for the suggestion.

**Comment by akosthekiss** [comment]
@rerobika 
- Thanks for the analysis. It's OK with me.
- As for the test case. So, is that true that the expected behaviour is an OOM situation? The `/tests/jerry` suite already has two files, `parser-oom.js` and `parser-oom2.js` that test such conditions. Cannot they show a way here?

**Comment by akosthekiss** [comment]
Note: Offline analysis has revealed that the approach used for parser OOM conditions cannot be applied here. So, for now, there seems to be no way for adding the failure-inducing test case to the regression test suite.

**Pull request merged**
